### ISSUE TITLE
Cut off of left side in country entrys

### ISSUE THREAD

**Issue by Shudushi** [itkach/slob#40] opened 2022-06-19 20:40 UTC
Hello itkach!

I use the "dewiki-20220601-NS0-ENTERPRISE-HTML.slob" (https://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiki20220601-slob/dewiki-20220601-NS0-ENTERPRISE-HTML.slob) from mhbraun with Aard 2 v0.53.

On country entries in that dictionaries, there is a cut off of left side in portrait (see attached screenshot). In landscape everything is fine.

I'm not clear if this is a thing of dictionary or Aard.

Regards

Shudushi

![Screenshot_20220619-222517_Aard 2](https://user-images.githubusercontent.com/61908206/174499509-d06376f8-7041-45cb-b1cb-0e7e17c377a4.jpg)

**Comment by bkuhls** [comment] 2022-06-19 21:08
duplicate of https://github.com/itkach/mw2slob/issues/12

**Closed** 2022-10-10 04:21 UTC
